---
- name: "Installing UFW"
  apt:
    name: ufw
    state: present

- name: "Setting deny anything by default"
  ufw:
    policy: deny

- name: "Setting allow any outgoing traffic"
  ufw:
    policy: allow
    direction: outgoing

- name: "Setting allow remote access to ssh from anywhere"
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: "Setting allow public ports from anywhere if exists"
  ufw:
    rule: allow
    port: '{{item}}'
    proto: tcp
  loop: '{{public_ports}}'
  when: public_ports is defined

- name: "Enabling UFW"
  ufw:
    state: enabled
